version: '3'
services:
  lb:
    image: nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    depends_on:
      - db
      - redis
    build: .
    env_file:
      - .env
    environment:
      - DB_CONNECTION_URL=postgresql+psycopg2://autochemplete:${AUTOCHEMPLETE_DB_PASSWORD}@db:5432/autochemplete

  redis:
    image: "redis"
    ports:
      - "127.0.0.1:6379:6379"

  db:
    image: postgres
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=autochemplete
      - POSTGRES_PASSWORD=${AUTOCHEMPLETE_DB_PASSWORD}
      - POSTGRES_DB=autochemplete

  migrator:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.migrations
    command: >
      sh -c "sleep 5 &&
            poetry run alembic upgrade head"
    environment:
      - DB_CONNECTION_URL=postgresql+psycopg2://autochemplete:${AUTOCHEMPLETE_DB_PASSWORD}@db:5432/autochemplete
    volumes:
      - .:/tmp

  analysis:
    depends_on:
      - db
    image: "jupyter/scipy-notebook"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - notebook:/home/joyvan/work:rw

volumes:
  db-data:
  notebook:
